version: '3.1'

services:

  redmine:
    # バージョン5は2022/03にリリースされたばかり。2022/05時点では、枯れているバージョン4を使用することとする。
    image: redmine:4
    restart: always
    ports:
      - 8080:3000
    environment:
      # :-, :? などの意味は以下参照 https://docs.docker.com/compose/environment-variables/
      REDMINE_DB_MYSQL: "${REDMINE_DB_MYSQL:-db}"
      REDMINE_DB_PASSWORD: "${REDMINE_DB_PASSWORD:?}"
      REDMINE_SECRET_KEY_BASE: "${REDMINE_SECRET_KEY_BASE}"
    volumes:
      - redmine-files:/usr/src/redmine/files/

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:?}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:?}"
    volumes:
      - ./my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf
      - db-data:/var/lib/mysql/

volumes:
  redmine-files:
  db-data:
