version: '3.1'

services:

  redmine:
    # バージョン5は2022/03にリリースされたばかり。2022/05時点では、枯れているバージョン4を使用することとする。
    image: redmine:4
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - ./my-custom.cnf:/etc/mysql/conf.d/my-custom.cnf
      - db-data:/var/lib/mysql/

volumes:
  db-data:
